### ISSUE TITLE
Update Sync Strategy to handle Default Values

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-intercom#1]
Here's an update to the sync scenario that we need to implement.

------------------------------------------------------------------
# The Problem with the current sync strategy:

`hull_user.first_name → intercom_user.first_name`

- If we don't do this, the Intercom User could have no values for `first_name` (same thing with all other standard fields.)

- If we do this in a naive way, Intercom `first_name` will be overwritten everytime.

- We only want to do this for standard fields for now, otherwise we end up needing to store a duplicate version of every field we send to intercom stored as a local value under the `intercom` source.

------------------------------------------------------------------

# The solution:

Have an "overwrite intercom value" checkbox for each field.
It sets the value of `first_name` only if the Intercom value of `first_name` is NULL.

#### When **checked**, we do the sync like this: 

`hull_user.first_name → intercom_user.first_name`

#### When **UNchecked**, we do the sync like this:

`hull_user.intercom.first_name || hull_user.first_name → intercom_user.first_name`

Salesforce API has a value setter that works like this, but Intercom does not. so the solution is to use the local value which we already know. It's not as reliable but it should work most of the time. We could later add "If user isn't already fetched, then fetch it before trying to set the value, store it in user profile and use api return to check for value"

------------------------------------------------------------------

# Recap

🌎 = Hull
🍅 = Intercom
🌕 = Clearbit

### Hull → Intercom
`🌎.first_name → 🍅.first_name`. 

"Intercom Wins":  
`(🌎.🍅.first_name || 🌎.first_name) → 🍅.first_name`

### Intercom → Hull
`🍅.first_name → 🌎.🍅.first_name`

### Hull → Intercom
`🌎.🌕.company → 🍅.company_name`

### Intercom → Hull
`🍅.company_name → 🌎.🍅.company_name`

**Comment by michaloo** [comment]
That sync scenario is implemented here:
https://github.com/hull-ships/hull-intercom/blob/master/server/lib/sync-agent/user-mapping.js#L120
