### ISSUE TITLE
Use user_id when available to update hull user

### ISSUE THREAD

**Issue by sbellity** [hull-ships/hull-intercom#17]
Use strategy similar to the one used on segment on hull user lookup : 

https://github.com/hull-ships/hull-segment/blob/develop/server/scope-hull-client.js

here : 
https://github.com/hull-ships/hull-intercom/blob/abccb04540f464f1669d67a19cc6c87c3fd1babd/server/lib/sync-agent/events-agent.js#L209

https://github.com/hull-ships/hull-intercom/blob/abccb04540f464f1669d67a19cc6c87c3fd1babd/server/lib/sync-agent/index.js#L71

and 

https://github.com/hull-ships/hull-intercom/blob/fa57b14e1ec5ee02ec3a6831b849bde23a8b3450/server/controller/jobs.js#L110

**Comment by sbellity** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use intercom user_id to lookup hull user when possible](https://trello.com/c/828KWcxJ/127-use-intercom-user-id-to-lookup-hull-user-when-possible)

**Comment by michaloo** [comment]
Done in #23
