### ISSUE TITLE
Update User creation strategy from Intercom

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-intercom#2]
Right now, users that were not already present in Hull are created with a `created_at==now()` and `last_seen_at==undefined`. This is expected with our current sync strategy of sandboxing each connector's values. However it generates less-than-optimal records.

We could safely setup smarter strategies by updating the root fields from the Hull user whenever they're not already set (`setIfNull`).

We should use @sbellity's APIs to "set If null" those values from the ones retrieved from Intercom.
i.e.: 

```js
  const default_fields = _.pick(intercom_user, 'first_name', 'last_name', 'last_seen_at', 'created_at' /* ... */);
  const new_user = { ...default_fields, ...user }
/*
  user.first_name ||= intercom.first_name
  user.last_name ||= intercom.last_name
  user.created_at ||= intercom.created_at
  user.last_seen_at ||= intercom.last_seen_at 
*/
```

We could also explore a strategy (togglable) where Intercom overwrites standard Hull fields,
It would work like this, where it only changes root values when intercom values change:

```js
const { first_name } = intercom_user;
if (first_name !== hull_user.intercom.first_name) {
  traits({ first_name });
  traits({ first_name }, { source : "intercom" });
}
```

> As a sidenote, could multiple, debounced traits efficiently be flattened to one call by the client library?

@sbellity @michaloo Discuss?

**Comment by michaloo** [comment]
Is `setIfNull` a part of Hull core API?

From ship perspective we cannot compare intercom field to hull field in case of actions triggered on intercom side. Except some minor cases we cannot even tell if the user already exists in hull database. Most convenient way would be to add more info to the mapping of standard fields and save them in `setIfNull` strategy to Hull API.

**Comment by sbellity** [comment]
Actually it should look like this : 

```js
const { first_name } = intercom_user;
if (first_name !== hull_user.intercom.first_name) {
  traits({ first_name: { operation: 'setIfNull', value: first_name } });
  traits({ first_name }, { source : "intercom" });
}
```

**Comment by michaloo** [comment]
While we can't do easy comparison like `first_name !== hull_user.intercom.first_name` we can end up having `setIfNull` calls for selected fields.
The only problem is that we don't have separate first, last_name fields on intercom:
https://developers.intercom.com/reference#section-user-object
so we need to adjust the setIfNull for full `name`
