### ISSUE TITLE
Companies are wrong

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-intercom#6]
Companies are set to values that shouldn't be. @michaloo do you see this issue on your end? Can you explain where those MongoIDs come from ?

![screen shot 2016-12-01 at 12 12 58](https://cloud.githubusercontent.com/assets/9458/20791958/ca70d756-b7bf-11e6-9096-a65bae4dc3ec.png)

**Comment by michaloo** [comment]
@unity could you tell me what is the error prone mapping setup?
The companies hardcoded mapping is in intercom -> hull direction.

**Comment by michaloo** [comment]
It comes from other Intercom integration. Not effect of ship behavior.
