### ISSUE TITLE
Intercom Companies array containes duplicate and empty values

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-intercom#7]
For User id 561fba41450f34efa5000019 (http://dashboard.hullbeta.io/users/561fba41450f34efa5000019) the Intercom "companies" hash is messy with duplicate values and empty values. We should `_.sort(uniq(_.compact()))` it.

```js
user = {
  "intercom": {
      "companies": [
        "Winners",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Winners",
        "",
        "",
        "Winners",
        "Winners",
        "Winners",
        "",
        "Winners",
        "",
        "",
        "",
        "",
        "Winners",
        "Winners",
        "Winners",
        "Winners",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ]
}
```

**Comment by unity** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Intercom Company Array is messy](https://trello.com/c/SWsprU74/105-intercom-company-array-is-messy)

**Comment by michaloo** [comment]
Fixed here:
https://github.com/hull-ships/hull-intercom/commit/45a69bc612d5c1e2c840a1f241c2e46f60b25bd6
