### ISSUE TITLE
We want to capture user lifecycle events from Intercom into Hull

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-intercom#8]
We want to subscribe to webhooks and capture the following user events.
For each, we want to specify with a checkbox wether to receive them or not.
We want these checkbox to be checked by default

Topics reference: https://developers.intercom.com/reference#topics

### `conversation.user.created`
```js
{
  event_name: "User started conversation",     
  properties: { ...data.item, topic, initiated: "user" },
  event_type: "conversation", 
  event_source: "intercom"
}
```

### `conversation.user.replied`
```js
{
  event_name: "User replied to conversation",  
  properties: { ...data.item, topic, initiated: "user" },
  event_type: "conversation", 
  event_source: "intercom"
}
```

### `conversation.admin.replied`
```js
{
  event_name: "Admin replied to conversation", 
  properties: { ...data.item, topic, initiated: "admin" },       
  event_type: "conversation", 
  event_source: "intercom"
}
```

### `conversation.admin.single.created`
```js
{
  event_name: "Admin started conversation",    
  properties: { ...data.item, topic, initiated: "admin" },       
  event_type: "conversation", 
  event_source: "intercom"
}
```

### `conversation.admin.noted`
```js
{
  event_name: "Admin added note",              
  properties: { ...data.item, topic },                          
  event_type: "conversation", 
  event_source: "intercom"
}
```

### `conversation.admin.assigned`
```js
{
  event_name: "Admin assigned conversation",   
  properties: { ...data.item, topic, assignee_id: assigneeId }, 
  event_type: "conversation", 
  event_source: "intercom"
}
```

### `conversation.admin.closed`
```js
{
  event_name: "Admin closed conversation",     
  properties: { ...data.item, topic, assignee_id: assigneeId }, 
  event_type: "conversation", 
  event_source: "intercom"
}
```

### `conversation.admin.opened`
```js
{
  event_name: "Admin opened conversation",     
  properties: { ...data.item, topic, assignee_id: assigneeId }, 
  event_type: "conversation", 
  event_source: "intercom"
}
```

### `user.unsubscribed`
```js
{
  event_name: "Unsubscribed from emails",      
  properties: { ...data.item, topic },                          
  event_type: "email" ,        
  event_source: "intercom"
}
```

### `user.email.updated`
```js
{
  event_name: "Updated email address",         
  properties: { ...data.item, topic },                          
  event_type: "email" ,        
  event_source: "intercom"
}
```

### `user.tag.created`
```js
{
  event_name: "Added Tag",                     
  properties: { ...data.item, topic, tag },                
  event_type: "tag" ,          
  event_source: "intercom"
}
```

### `user.tag.deleted`
```js
{
  event_name: "Removed Tag",                   
  properties: { ...data.item, topic, tag },                
  event_type: "tag" ,          
  event_source: "intercom"
}
```

**Comment by unity** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Intercom Events Support](https://trello.com/c/dC5FbIPm/42-intercom-events-support)

**Comment by michaloo** [comment]
Basic version started here:
https://github.com/hull-ships/hull-intercom/tree/feature/events-capture

**Comment by michaloo** [comment]
@unity I've a question about details of capturing event information. Below is the gist with full request from intercom:

https://gist.github.com/michaloo/b601dac8699da30549edff58f8364013

In the specs above for `user.tag.created` event you have: `properties: { ...data.item, topic, tag: tag }`:

`data.item` object is pretty big, it contains standard user field, do we want to save it all to event properties?

`tag: tag` should only capture the tag name as tag property of hull event?


And the last question: if we want to track events for hull segment tags?

**Comment by unity** [comment]
Yes. I had no idea the event was so deep ;)
- we only want the tag.
- we probably want to skip hull segment tags. We don't need this in the event list. We already have "entered segment" events

**Comment by michaloo** [comment]
For `conversation.admin.assigned`, we have following spec:
`{ ...data.item, topic, to: ownerId, admin: ownerId }`

and the data for that topic, as stated in docs (I cannot test it on free plan without CC):

```json
{
  "type": "conversation",
  "id": "147",
  "created_at": 1400850973,
  "updated_at": 1400857494,
  "conversation_message": {
    "type": "conversation_message",
    "subject": "",
    "body": "<p>Hi Alice,</p>\n\n<p> We noticed you using our Product,  do you have any questions?</p> \n<p>- Jane</p>",
    "author": {
      "type": "admin",
      "id": "25"
    },
    "attachments": [
      {
        "name": "signature",
        "url": "http://example.org/signature.jpg"
      }
    ]
  },
  "user": {
    "type": "user",
    "id": "536e564f316c83104c000020"
  },
  "assignee": {
    "type": "admin",
    "id": "25"
  },
  "open": true,
  "read": true,
  "conversation_parts": {
    "type": "conversation_part.list",
    "conversation_parts": [
      //... List of conversation parts
    ]
  },
  "tags": { "type": 'tag.list', "tags": [] } }
}
```

what fields we would like to capture here?

**Comment by unity** [comment]
It's hard without an api example indeed.
Here's what I would say (to be confirmed once we have an actual payload)

- `topic => payload.topic`
- `subject => payload.data.item.conversation_message.subject`
- `body => payload.data.item.conversation_message.body`
- `author_type => payload.data.item.conversation_message.author_type`
- `author_id => payload.data.item.conversation_message.author_id`
- `assignee_id => payload.data.item.assignee.id`

I'll update the above spec

**Comment by unity** [comment]
@michaloo updated the docs.

**Comment by michaloo** [comment]
Feature prepared here:
https://github.com/hull-ships/hull-intercom/pull/14
