### ISSUE TITLE
We want to be able to send select user events to Intercom

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-intercom#9]
We want to select a list of Hull event names from a field of type `event` and format `array` and start sending events that are listed to Intercom, same as we already do with the Segment connector

We want to have a checkbox to globally enable or disable event forwarding to Intercom

**Comment by unity** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Intercom Events Support](https://trello.com/c/dC5FbIPm/42-intercom-events-support)

**Comment by michaloo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [push (selected) events from hull to intercom](https://trello.com/c/Ptzgfhbd/123-push-selected-events-from-hull-to-intercom)

**Comment by michaloo** [comment]
@unity do we want to keep the save behaviour?
https://github.com/hull-ships/hull-segment/blob/develop/manifest.json#L57

Also I wanted to clarify what we understand by event `forwarding`. By your description above I understand it's just a turn on/off switch for events pushing.
Segment implementation suggests opposite direction
https://github.com/hull-ships/hull-segment/blob/develop/manifest.json#L63

**Comment by michaloo** [comment]
Prepared here:
https://github.com/hull-ships/hull-intercom/pull/16
